# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "rpi-trials"
BBFILE_PATTERN_rpi-trials = "^${LAYERDIR}/"
BBFILE_PRIORITY_rpi-trials = "10"

LAYERDEPENDS_rpi-trials = "core yocto openembedded-layer raspberrypi"

LAYERSERIES_COMPAT_rpi-trials = "wrynose"
