require conf/distro/poky.conf

DISTRO = "rpi-trials"
DISTRO_NAME = "RPi Trials Distro"
DISTRO_VERSION = "1.0"
DISTRO_CODENAME = "wrynose"

MAINTAINER = "RPi Trials Maintainer"

# Accept license flags required by this project
LICENSE_FLAGS_ACCEPTED += "synaptics-killswitch"
